stages:
  - test
  - build

Docker Goss Tests:
  stage: test
  tags:
    - goss
  script:
    - make goss

Build docker image:
  stage: build
  tags:
   - docker
  script:
   - make build CI_COMMIT_TAG=${CI_COMMIT_TAG:-latest}
   - docker-clean
   - docker push pyrmin.io/mongodb:${CI_COMMIT_TAG:-latest}
  only:
    - master
    - tags