Build docker image:
  tags:
   - docker
  script:
   - make build CI_BUILD_TAG=${CI_BUILD_TAG:-latest}
   - docker-clean
   - sudo /usr/bin/docker push pyrmin.io:5000/mongodb-testing:${CI_BUILD_TAG:-latest}