Build docker image:
  tags:
   - podman
  script:
   - make build CI_COMMIT_TAG=${CI_COMMIT_TAG:-latest}
   - buildah push --authfile ~/.auth.json docker.io/recteurlp/mongodb:${CI_COMMIT_TAG:-latest}
  only:
    - master
    - tags